### ISSUE TITLE
Optionally ignore fragment identifiers

### ISSUE THREAD

**Issue by vstepaniuk** [jaatroko/link-status-redux#16]
Is it possible to optionally ignore fragment identifiers in the links addresses?

**Comment by jaatroko** [comment]
Not practically, the fragment identifier is part of the URL stored in the browser history, and the history search (`browser.history.getVisits()`) uses strict(ish) matching. What _is_ trivial to do is to check whether the "base" page was visited, i.e. if the link URL is `http://site/page#frag` you can also/instead check `http://site/page`. But what I think you want is to check if the "base" page _with any fragment identifier_ was visited, and that is not practical (it is _possible_ to use a wider history search and do the matching and possible sorting in Javascript, but that would probably destroy performance).

Also note that with Javascript websites `#` can be used like `?` in CGI queries, i.e. the resulting document might be completely different depending on the fragment identifier used.
