### ISSUE TITLE
storage inspector?

### ISSUE THREAD

**Issue by rezad1393** [jaatroko/link-status-redux#21]
when i use this addon, in firefox storage inspector I see another source beside the opened page that related to this addon.
no other addon does this.
this is a bit confusing.
can this be fixed?

without this addon

![Screenshot_20190615_145007](https://user-images.githubusercontent.com/7523164/59550164-ffb0bc00-8f7c-11e9-9f32-840452501947.png)

with this addon

![Screenshot_20190615_145045](https://user-images.githubusercontent.com/7523164/59550166-017a7f80-8f7d-11e9-9031-83eb3f2774a6.png)

**Comment by jaatroko** [comment]
> no other addon does this.

I'm sure there are others that do this, it's just that LSR is probably the only one you've encountered.

> can this be fixed?

No. The storage inspector shows all origins in the page, including iframes. And the LSR popup overlay is an iframe, as that is the only (sane/secure(ish)) way for a WebExtension to have UI elements on top of the page area (you can see the LSR iframe in the inspector, at the bottom with id `e0fe7e79ef044e56993c0a0a6874baed`).

**Comment by rezad1393** [comment]
ok? so the only way to create overlays is iframes( because webexts in firefox made it that way?)
btw I have never encountered this before your addon.(and I have a LOT of addons installed)

maybe adding it as a item to right click menu for links would be better? 

but this is your addon. you know best and I wont push for a change.

**Comment by jaatroko** [comment]
Well, using an iframe is not the _only_ way, but the main point is that the overlay needs to be _part of the page DOM_. You can inject any elements, but not encapsulating the overlay in an iframe is much more fragile (wrt. DOM and CSS modification) and also might expose private information (see issue #7).
