### ISSUE TITLE
Overlink popup at mouse pointer is misplaced when the page is zoomed in or out

### ISSUE THREAD

**Issue by jaatroko** [jaatroko/link-status-redux#23]
Reported by user LostPacket in an AMO review.
Related: issue #12

If the overlink popup is configured to be at an offset from the mouse pointer and the page zoom factor (adjusted with Ctrl+ and Ctrl-) is not 100%, the popup is misplaced proportional to the zoom factor: too close to the top-left corner for zoom <100%, and too far for zoom >100%.

This could be fixed by detecting the zoom factor and compensating, but there seems to be no good way to detect the zoom factor. There is `window.devicePixelRatio`, but that also includes DPI scaling and DPI scaling is not a problem: on my test on a 192 DPI screen `window.devicePixelRatio` is 2 at 100% zoom and the popup is correctly placed. So while it could be used to fix this on standard DPI screens, it would break the placement on HiDPI screens even at 100% zoom.

The issue stems from the need to use global mouse coordinates (`MouseEvent.screenX`) in order to get the correct position wrt the tab window even from within an iframe. But it seems that the global coordinates are only DPI scaled, whereas the page (and presumably `MouseEvent.clientX` and `MouseEvent.pageX` as well) are DPI scaled and then further scaled by the zoom factor. And, being just a page element, the popup position is defined in page pixels which are DPI+zoom scaled.

A web search returns a few hits for detecting the zoom factor, but they all seem to be horrible contraptions of questionable reliablity and/or include a fair amount of processing or page elements and CSS tricks; not very suitable for a WebExtension. So unfortunately this bug will remain unfixed until there is an proper/acceptable way to detect the zoom factor.

**Comment by Rekur** [comment]
Thank you for an update. OK, sounds complicated indeed...

Have you by any chance examined how [URL Tooltip WE](https://addons.mozilla.org/en-US/firefox/addon/url-tooltip-we) manages to seemingly properly position the popup at all zoom levels? (My Windows DPI scaling is at 100%, BTW.)

**Comment by jaatroko** [comment]
> Have you by any chance examined how [URL Tooltip WE](https://addons.mozilla.org/en-US/firefox/addon/url-tooltip-we) manages to seemingly properly position the popup at all zoom levels? (My Windows DPI scaling is at 100%, BTW.)

Thanks for the pointer. Only took a cursory reading of the code and then checking mozdev to find that Firefox does indeed have [an API for zoom level (changes)](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onZoomChange). I'm just wondering how I managed to miss this in my web searches; probably because this is an API for WE background scripts, and the web is full problems (and occasionally, solutions :) related to website JS (comparable to content scripts).

Anyway, I will take a look at this when I have time, but at first glance it looks promising.

**Comment by Rekur** [comment]
Thank you for an ultra-prompt response, Juha! You probably won't need this, but I realized that there are also some dictionary/translation add-ons that display a pop-up next to the pointer on hover. But like I said, if onZoomChange() suffices, then all the better. Thanks again, and keep up the good work!

**Comment by jaatroko** [comment]
Fixed in version 3.11. The scaling of the overlink popup can cause artifacts, see comment in issue #12 for details.

**Comment by Rekur** [comment]
Yes, all seems well with 3.11 under Win7/SP1/x64/FF70.0.1. Thank you, Juha!
