### ISSUE TITLE
show status of links without mouseover

### ISSUE THREAD

**Issue by accelaptd** [jaatroko/link-status-redux#24]
would you consider adding the capability to highlight the links visually without mouseover? there are similar extensions available but neither work uniformly across all sites.

[bookmark highlighter](https://addons.mozilla.org/en-GB/firefox/addon/bookmark-highlighter/) works unevenly across sites. 

[visited link enabler](https://addons.mozilla.org/en-GB/firefox/addon/visited-link-enabler/) works across all sites (that i use) but only works with visited links.

your extension works across all sites and with both bookmarked/visited links, but requires mouseover.  i wonder if highlighted links of different colours/styles for links/bookmarks could be achieved with your plug-in through forcing custom css with another extension, or if this could be added to your extension as a feature.

thanks! for your work on the extension (essential and incredibly useful for me) and reading/considering my request.

**Comment by jaatroko** [comment]
No, this is outside the scope of LSR and won't be implemented.

For visited links this could probably be achieved straightforwardly with (user-origin) CSS and the `:visited` selector (and that's probably what the visited link enabler extension uses). However, there is no `:bookmarked` selector in CSS, so you would have to modify the DOM: check every link on the page for bookmarked, and then add a CSS class. You would also have to do this for any links that are added dynamically to the page. This may be the reason why the bookmark highlighter extension works "unevenly".
