### ISSUE TITLE
Display link status in the location bar

### ISSUE THREAD

**Issue by Keith94** [jaatroko/link-status-redux#3]
I'm wondering if that's possible with the current APIs.

**Comment by jaatroko** [comment]
For the legacy version, this can be done with [Status-4-Evar](https://addons.mozilla.org/en-US/firefox/addon/status-4-evar/) (_Status>General>Links_ and _Status>Location Bar_ in the preferences dialog), LSR works with all of S4E's link display options (S4E is the only extension LSR has explicit support for).

As for the WebExtension (which I will push to github after a few finishing touches), there is no API for it, so no can do. (There _are_ security considerations in obscuring the location bar, so I'm not that surprised.)

**Comment by Keith94** [comment]
Unfortunate there's no API for it :-(

I'll wait for the new version nonetheless. Thanks for your answer!
