### ISSUE TITLE
German translator wanted

### ISSUE THREAD

**Issue by jaatroko** [jaatroko/link-status-redux#39]
Version 3.13 added UI changes that needed to be translated. Unfortunately the German translator could not be reached, so the German translation for 3.13 is incomplete with English placeholders.

If you wish to contribute, let me know here and/or make a pull request. As always with translations, you should be fluent, preferrably native, in the target language.

If no one volunteers, I will have to decide whether to keep the translation incomplete, or to remove it entirely.

**Comment by rvan-tgm** [comment]
I could do that for you, i'll make a PR in the next few days!

**Comment by jaatroko** [comment]
Resolved by PR #40.
