### ISSUE TITLE
Option to color all visited links

### ISSUE THREAD

**Issue by advait404** [jaatroko/link-status-redux#42]
I am using the below css script to change the color of links, and it would be nice if the extension had a built-in option for this.
```
/* ==UserStyle==
@name           Colour Visited Links
@version        1.0
@description    color links
@include http://*/*
@include https://*/*
==/UserStyle== */
A:visited { color: #ffafff ! important }
```

**Comment by jaatroko** [comment]
I don't see LSR as the right place for this. In addition to it being (a bit) out of scope:

1. LSR does everything it can to keep its effects inside the link overlay popup and to *not* affect the appearance of the website.
2. LSR does not (and will not) have a toolbar button or context menu options, so if you wanted to toggle this on and off you would have to do it from the options page, which is not very convenient.
3. Even if toggling from the options page doesn't deter you, LSR has no site-specifity, so the feature would be global, not per-site.

If you want this feature to be always on and global, then what you are doing now is sufficient: inconvenience does not matter much if you are only going to set it once and then forget it. If you want toggleability or site-specific rules, then I would suggest you find an add-on dealing with user CSS that has those features. (There looks to be many user CSS add-ons, but I'm not informed enough to recommend any specific one.)
