### ISSUE TITLE
iframe blocking with ublock (for some website) make this addon popup disappear

### ISSUE THREAD

**Issue by rezad1393** [jaatroko/link-status-redux#43]
iframe blocking with ublock (for some website) make this addon popup disappear.

**Comment by jaatroko** [comment]
Can you give an example how to reproduce this? I tried the "simple" way i.e. blocked everything from uBlock Origin's advanced user interface, and LSR's popup shows up fine (at least on the site I tested on).

But generally, the addon popup is inside a transparent, fullscreen iframe injected by the addon (see issue #7). So if something manages to (permanently) remove this iframe from the document, there may not be anything LSR can do about it.

**Comment by rezad1393** [comment]
I lost the website I had this issue for (I am trying to report issues with foss software after some time so I forgot some details) 
I searched in ublock filters and I this this website https://allporncomic.com/ has it  as this allporncomic.com##iframe ( I am not sure because it is blocked in my country as porn and I dont have a vpn to test it right now) .

**Comment by rezad1393** [comment]
thanks.
that was my point but you say that it cant be fixed. 
didn't know about the exception in ublock.
I think I close this now.
